### ISSUE TITLE
conda package recipe still uses a version of BioPython that needs alphabet to be specified

### ISSUE THREAD

**Issue by KatSteinke** [scwatts/hicap#7]
When I installed hicap 1.0.4 from conda and tried to analyze a genome with it, it failed with the following error:
```
Traceback (most recent call last):
  File "/home/kat/miniconda3/envs/hicap_test/bin/hicap", line 10, in <module>
    sys.exit(main())
  File "/home/kat/miniconda3/envs/hicap_test/lib/python3.6/site-packages/hicap/main.py", line 71, in main
    report.write_outputs(locus_data, args)
  File "/home/kat/miniconda3/envs/hicap_test/lib/python3.6/site-packages/hicap/report.py", line 72, in write_outputs
    Bio.SeqIO.write(genbank_data, fh, 'genbank')
  File "/home/kat/miniconda3/envs/hicap_test/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 517, in write
    count = writer_class(fp).write_file(sequences)
  File "/home/kat/miniconda3/envs/hicap_test/lib/python3.6/site-packages/Bio/SeqIO/Interfaces.py", line 237, in write_file
    count = self.write_records(records)
  File "/home/kat/miniconda3/envs/hicap_test/lib/python3.6/site-packages/Bio/SeqIO/Interfaces.py", line 222, in write_records
    self.write_record(record)
  File "/home/kat/miniconda3/envs/hicap_test/lib/python3.6/site-packages/Bio/SeqIO/InsdcIO.py", line 815, in write_record
    self._write_the_first_line(record)
  File "/home/kat/miniconda3/envs/hicap_test/lib/python3.6/site-packages/Bio/SeqIO/InsdcIO.py", line 624, in _write_the_first_line
    raise ValueError("Need a Nucleotide or Protein alphabet")
ValueError: Need a Nucleotide or Protein alphabet
```

With 1.0.3, the issue didn't occur. From what it looks like to me, the [conda package recipe](https://bioconda.github.io/recipes/hicap/README.html#package-hicap) for hicap still requires `BioPython==1.72,` which predates the deprecation of `Bio.Alphabet` - I assume for the current version of hicap, it should be 1.78 or higher?

**Comment by scwatts** [comment]
Hi @KatSteinke, thanks so much for opening this issue. I've created a Bioconda PR to fix the problem in the hicap recipe - I'll test out the build artefacts and then let you know once it is merged/available!

**Comment by scwatts** [comment]
The Conda package has now been updated and I've successfully tested with:

```bash
conda create -y -n hicap -c bioconda -c conda-forge hicap
conda activate hicap

wget -P input/ https://raw.githubusercontent.com/scwatts/hicap/v1.0.4/example/Hi75.fasta

mkdir -p output/
hicap --query_fp input/Hi75.fasta --output_dir output/
```

In addition, I have also implemented a simple end-to-end test in the relevant GitHub Action workflow that will help catch this type of problem.

Thank you again for opening the issue!
